// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWTOuM5D_Tkw32WQDs_NQ5DHMiFT7uvI',
    appId: '1:1087187692024:web:d8cb752a43efbc466b0e0d',
    messagingSenderId: '1087187692024',
    projectId: 'zikr-1b219',
    authDomain: 'zikr-1b219.firebaseapp.com',
    storageBucket: 'zikr-1b219.firebasestorage.app',
    measurementId: 'G-EMWT3ZSL1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCngyLPvdCuCLOSFR0Ljc8p9iRQ1jw1iU8',
    appId: '1:1087187692024:android:9968afd9b7a143b36b0e0d',
    messagingSenderId: '1087187692024',
    projectId: 'zikr-1b219',
    storageBucket: 'zikr-1b219.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACcbT19vXwI_NmebQrr34x2OTcLweWiHI',
    appId: '1:1087187692024:ios:ce2dc448162fa01a6b0e0d',
    messagingSenderId: '1087187692024',
    projectId: 'zikr-1b219',
    storageBucket: 'zikr-1b219.firebasestorage.app',
    iosClientId: '1087187692024-69dsgd5uss54mhfdukp03l18moigdnvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.zikr',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACcbT19vXwI_NmebQrr34x2OTcLweWiHI',
    appId: '1:1087187692024:ios:ce2dc448162fa01a6b0e0d',
    messagingSenderId: '1087187692024',
    projectId: 'zikr-1b219',
    storageBucket: 'zikr-1b219.firebasestorage.app',
    iosClientId: '1087187692024-69dsgd5uss54mhfdukp03l18moigdnvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.zikr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChWTOuM5D_Tkw32WQDs_NQ5DHMiFT7uvI',
    appId: '1:1087187692024:web:d606ff67412bd3de6b0e0d',
    messagingSenderId: '1087187692024',
    projectId: 'zikr-1b219',
    authDomain: 'zikr-1b219.firebaseapp.com',
    storageBucket: 'zikr-1b219.firebasestorage.app',
    measurementId: 'G-GKTSTXREWT',
  );
}
